insert into banners (image_path, is_active) values ('https://printbucket.com/content/images/products/info/poster-print.png', false);

INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, invited_at, confirmation_token, confirmation_sent_at, recovery_token, recovery_sent_at, email_change_token_new, email_change, email_change_sent_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, created_at, updated_at, phone, phone_confirmed_at, phone_change, phone_change_token, phone_change_sent_at, email_change_token_current, email_change_confirm_status, banned_until, reauthentication_token, reauthentication_sent_at, is_sso_user, deleted_at) VALUES ('00000000-0000-0000-0000-000000000000', '0a624bb9-608f-42d8-b177-0e8aa3755459', 'authenticated', 'authenticated', 'user@gmail.com', '$2a$10$rSnVS8iNto.nffXJ.2fYwe6k.Yg7zNT/qYbi2alHRqaZFYuU7I8YW', '2023-04-15 08:50:00.853673+00', NULL, '', NULL, '', NULL, '', '', NULL, NULL, '{"provider": "email", "providers": ["email"]}', '{}', NULL, '2023-04-15 08:50:00.849096+00', '2023-04-15 08:50:00.853801+00', NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL);
INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, invited_at, confirmation_token, confirmation_sent_at, recovery_token, recovery_sent_at, email_change_token_new, email_change, email_change_sent_at, last_sign_in_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, created_at, updated_at, phone, phone_confirmed_at, phone_change, phone_change_token, phone_change_sent_at, email_change_token_current, email_change_confirm_status, banned_until, reauthentication_token, reauthentication_sent_at, is_sso_user, deleted_at) VALUES ('00000000-0000-0000-0000-000000000000', '8a9c4b3b-6f8e-4d9f-9fcf-7f9c8a56c1c6', 'authenticated', 'authenticated', 'user2@gmail.com', '$2a$10$rSnVS8iNto.nffXJ.2fYwe6k.Yg7zNT/qYbi2alHRqaZFYuU7I8YW', '2023-04-15 08:50:00.853673+00', NULL, '', NULL, '', NULL, '', '', NULL, NULL, '{"provider": "email", "providers": ["email"]}', '{}', NULL, '2023-04-15 08:50:00.849096+00', '2023-04-15 08:50:00.853801+00', NULL, NULL, '', '', NULL, '', 0, NULL, '', NULL, false, NULL);


-- books for user 1
insert into books (title, author, description, image_path, owner_id, condition) values ('Book 1', 'Author 1', 'Description 1', 'https://s26162.pcdn.co/wp-content/uploads/2018/02/gatsby-original2.jpg', '0a624bb9-608f-42d8-b177-0e8aa3755459', 1);
insert into books (title, author, description, image_path, owner_id, condition) values ('Book 2', 'Author 2', 'Description 2', 'https://framerusercontent.com/images/l2ikaGhmnRAiAjYz4cCRQzR7ds.jpeg', '0a624bb9-608f-42d8-b177-0e8aa3755459', 2);
insert into books (title, author, description, image_path, owner_id, condition) values ('Book 3', 'Author 3', 'Description 3', 'https://ichef.bbci.co.uk/images/ic/480xn/p08g0rs4.jpg.webp', '8a9c4b3b-6f8e-4d9f-9fcf-7f9c8a56c1c6', 3);


-- Generate 100 books under user id: 3c05c224-4111-48f5-b680-5a7d47d9b96d
insert into books (title, author, description, image_path, owner_id, condition) values
('To Kill a Mockingbird', 'Harper Lee', 'A powerful story of racial injustice and loss of innocence in the American South', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1553383690i/2657.jpg', (select id from auth.users limit 1), 2),
('1984', 'George Orwell', 'A dystopian novel set in a totalitarian society', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1657781256i/61439040.jpg', (select id from auth.users limit 1), 1),
('Pride and Prejudice', 'Jane Austen', 'A classic romance novel about the relationship between Elizabeth Bennet and Mr. Darcy', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1320399351i/1885.jpg', (select id from auth.users limit 1), 3),
('The Great Gatsby', 'F. Scott Fitzgerald', 'A story of decadence and excess in the Jazz Age', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1490528560i/4671.jpg', (select id from auth.users limit 1), 2),
('The Catcher in the Rye', 'J.D. Salinger', 'A story of teenage alienation and loss', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1398034300i/5107.jpg', (select id from auth.users limit 1), 1),
('Lord of the Flies', 'William Golding', 'A group of British boys descent into savagery when stranded on an uninhabited island', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327869409i/7624.jpg', (select id from auth.users limit 1), 2),
('The Hobbit', 'J.R.R. Tolkien', 'A fantasy novel about Bilbo Baggins journey with a group of dwarves', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546071216i/5907.jpg', (select id from auth.users limit 1), 1),
('Fahrenheit 451', 'Ray Bradbury', 'A dystopian novel about a future society where books are banned', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1383718290i/13079982.jpg', (select id from auth.users limit 1), 3),
('The Alchemist', 'Paulo Coelho', 'A philosophical novel about a young Andalusian shepherd and his journey to find treasure', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1654371463i/18144590.jpg', (select id from auth.users limit 1), 2),
('Brave New World', 'Aldous Huxley', 'A dystopian novel about a futuristic World State', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1575509280i/5129.jpg', (select id from auth.users limit 1), 1),
('The Little Prince', 'Antoine de Saint-Exupéry', 'A poetic tale about a young prince who visits various planets', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1367545443i/157993.jpg', (select id from auth.users limit 1), 2),
('Animal Farm', 'George Orwell', 'An allegorical novella about the Soviet Union', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1325861570i/170448.jpg', (select id from auth.users limit 1), 3),
('The Da Vinci Code', 'Dan Brown', 'A mystery thriller involving a conspiracy within the Catholic Church', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1579621267i/968.jpg', (select id from auth.users limit 1), 1),
('The Road', 'Cormac McCarthy', 'A post-apocalyptic tale of a father and son''s journey', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1600241424i/6288.jpg', (select id from auth.users limit 1), 2),
('One Hundred Years of Solitude', 'Gabriel García Márquez', 'A multi-generational saga of the Buendía family', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327881361i/320.jpg', (select id from auth.users limit 1), 1),
('The Kite Runner', 'Khaled Hosseini', 'A story of friendship, betrayal, and redemption in Afghanistan', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1579036753i/77203.jpg', (select id from auth.users limit 1), 2),
('The Hunger Games', 'Suzanne Collins', 'A young adult novel about a dystopian future where children fight to the death', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1586722975i/2767052.jpg', (select id from auth.users limit 1), 3),
('The Book Thief', 'Markus Zusak', 'A story about a young girl living in Nazi Germany', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1522157426i/19063.jpg', (select id from auth.users limit 1), 1),
('The Chronicles of Narnia', 'C.S. Lewis', 'A series of fantasy novels about the magical world of Narnia', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1449868701i/11127.jpg', (select id from auth.users limit 1), 2),
('The Handmaid''s Tale', 'Margaret Atwood', 'A dystopian novel about a theocratic society where women are stripped of their rights', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1578028274i/38447.jpg', (select id from auth.users limit 1), 1);

insert into books (title, author, description, image_path, owner_id, condition) values
('The Odyssey', 'Homer', 'An ancient Greek epic poem about Odysseus''s journey home', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1390173285i/1381.jpg', (select id from auth.users limit 1), 2),
('Crime and Punishment', 'Fyodor Dostoevsky', 'A psychological novel about a poor student who commits murder', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1382846449i/7144.jpg', (select id from auth.users limit 1), 3),
('The Picture of Dorian Gray', 'Oscar Wilde', 'A Gothic novel about a man who stays eternally young while his portrait ages', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546103428i/5297.jpg', (select id from auth.users limit 1), 1),
('Moby Dick', 'Herman Melville', 'The epic tale of Captain Ahab''s quest for revenge against a white whale', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327940656i/153747.jpg', (select id from auth.users limit 1), 3),
('Jane Eyre', 'Charlotte Brontë', 'A Gothic romance about an orphan who becomes a governess', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1557343311i/10210.jpg', (select id from auth.users limit 1), 1);


insert into books (title, author, description, image_path, owner_id, condition) values
('Wuthering Heights', 'Emily Brontë', 'A tale of passionate love and revenge on the Yorkshire moors', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388212715i/6185.jpg', (select id from auth.users limit 1), 2),
('The Count of Monte Cristo', 'Alexandre Dumas', 'A story of revenge and redemption in 19th century France', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1611834134i/7126.jpg', (select id from auth.users limit 1), 3),
('The Lord of the Rings', 'J.R.R. Tolkien', 'An epic high-fantasy trilogy about the quest to destroy the One Ring', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1566425108i/33.jpg', (select id from auth.users limit 1), 1),
('Don Quixote', 'Miguel de Cervantes', 'The story of a man who loses his sanity and becomes a knight errant', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546112331i/3836.jpg', (select id from auth.users limit 1), 2),
('The Divine Comedy', 'Dante Alighieri', 'An epic poem describing Dante''s journey through Hell, Purgatory, and Paradise', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1390760180i/6656.jpg', (select id from auth.users limit 1), 3),
('Les Misérables', 'Victor Hugo', 'The story of ex-convict Jean Valjean and his path to redemption', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1411852091i/24280.jpg', (select id from auth.users limit 1), 1),
('The Brothers Karamazov', 'Fyodor Dostoevsky', 'A philosophical novel that delves into faith, doubt, and morality', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1427728126i/4934.jpg', (select id from auth.users limit 1), 2),
('War and Peace', 'Leo Tolstoy', 'An epic novel of Russian society during the Napoleonic Era', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1413215930i/656.jpg', (select id from auth.users limit 1), 3),
('The Old Man and the Sea', 'Ernest Hemingway', 'The story of an aging Cuban fisherman who struggles with a giant marlin', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1329189714i/2165.jpg', (select id from auth.users limit 1), 1),
('The Name of the Rose', 'Umberto Eco', 'A historical murder mystery set in an Italian monastery', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1415375471i/119073.jpg', (select id from auth.users limit 1), 2),
('The Stranger', 'Albert Camus', 'A story about an ordinary man who commits a murder', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1590930002i/49552.jpg', (select id from auth.users limit 1), 1),
('The Master and Margarita', 'Mikhail Bulgakov', 'A satirical tale about Satan''s visit to the Soviet Union', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327867963i/117833.jpg', (select id from auth.users limit 1), 2),
('The Metamorphosis', 'Franz Kafka', 'A novella about a man who wakes up one day transformed into an insect', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1646444605i/485894.jpg', (select id from auth.users limit 1), 1),
('One Flew Over the Cuckoo''s Nest', 'Ken Kesey', 'A story set in a psychiatric hospital about rebellion against authority', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1516211014i/332613.jpg', (select id from auth.users limit 1), 2),
('The Bell Jar', 'Sylvia Plath', 'A semi-autobiographical novel about mental illness and society''s expectations', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1554582218i/6514.jpg', (select id from auth.users limit 1), 3),
('Slaughterhouse-Five', 'Kurt Vonnegut', 'An anti-war novel that combines science fiction and historical events', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1440319389i/4981.jpg', (select id from auth.users limit 1), 1),
('The Scarlet Letter', 'Nathaniel Hawthorne', 'A historical novel about sin and guilt in Puritan New England', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1404810944i/12296.jpg', (select id from auth.users limit 1), 2),
('The Sun Also Rises', 'Ernest Hemingway', 'A story of the Lost Generation in post-World War I Europe', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1509802323i/3876.jpg', (select id from auth.users limit 1), 3);

insert into books (title, author, description, image_path, owner_id, condition) values
('The Iliad', 'Homer', 'An ancient Greek epic poem about the Trojan War', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388188509i/1371.jpg', (select id from auth.users limit 1), 1),
('Dracula', 'Bram Stoker', 'A Gothic horror novel about Count Dracula''s attempt to move to England', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1387151694i/17245.jpg', (select id from auth.users limit 1), 2),
('The Adventures of Huckleberry Finn', 'Mark Twain', 'A story about a young boy''s journey down the Mississippi River', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546096879i/2956.jpg', (select id from auth.users limit 1), 3),
('Catch-22', 'Joseph Heller', 'A satirical novel about the absurdity of war', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1463157317i/168668.jpg', (select id from auth.users limit 1), 1),
('The Three Musketeers', 'Alexandre Dumas', 'A historical adventure novel set in 17th century France', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1320436982i/7190.jpg', (select id from auth.users limit 1), 3),
('The Wind in the Willows', 'Kenneth Grahame', 'A children''s novel about anthropomorphized animals in the English countryside', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1630642716i/5659.jpg', (select id from auth.users limit 1), 2),
('Frankenstein', 'Mary Shelley', 'A Gothic novel about a scientist who creates a sapient creature', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1631088473i/35031085.jpg', (select id from auth.users limit 1), 1),
('The Call of the Wild', 'Jack London', 'A story about a dog''s journey from domesticated life to the Alaskan wild', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1452291694i/1852.jpg', (select id from auth.users limit 1), 2),
('The Secret Garden', 'Frances Hodgson Burnett', 'A novel about a young girl who discovers a hidden garden', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327873635i/2998.jpg', (select id from auth.users limit 1), 1),
('Little Women', 'Louisa May Alcott', 'A story about four sisters growing up during the American Civil War', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1562690475i/1934.jpg', (select id from auth.users limit 1), 2);
