name: book_swap
description: A book swap app

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  assorted_layout_widgets: ^10.0.4
  auto_route: ^9.2.2
  dotted_line: ^3.2.3
  autoverpod: ^0.0.3
  bot_toast: ^4.1.3
  custom_rating_bar: ^3.0.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.8
  dartx: ^1.2.0
  desktop_drop: ^0.5.0
  device_info_plus: ^11.2.0
  dotted_border: ^2.1.0
  easy_debounce: ^2.0.3
  fast_immutable_collections: ^11.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_image_compress: ^2.4.0
  flutter_riverpod: any
  form_builder_validators: ^11.1.1
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  hive_ce: ^2.8.0
  hive_ce_flutter: ^2.1.0
  hooks_riverpod: ^2.6.1
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  kimapp:
    git:
      url: https://github.com/pckimlong/kimapp.git
      ref: master
      path: packages/kimapp
  kimapp_supabase_helper:
    git:
      url: https://github.com/pckimlong/kimapp.git
      ref: master
      path: packages/kimapp_supabase_helper
  kimapp_utils:
    git:
      url: https://github.com/pckimlong/kimapp.git
      ref: master
      path: packages/kimapp_utils
  mocktail: ^1.0.4
  octo_image: ^2.1.0
  package_info_plus: ^8.1.2
  page_transition: ^2.1.0
  path_provider: ^2.1.5
  responsive_framework: ^1.5.1
  riverpod: any
  riverpod_annotation: ^2.6.1
  skeletonizer: ^1.4.3
  stack_trace: ^1.12.1
  supabase_flutter: ^2.8.2
  talker_flutter: ^4.6.10
  talker_riverpod_logger: ^4.6.10
  timeago: ^3.7.0
dev_dependencies:
  auto_route_generator: ^9.0.0
  autoverpod_generator: ^0.0.2
  build_runner: ^2.4.14
  change_app_package_name: ^1.5.0
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.2
  kimapp_generator:
    git:
      url: https://github.com/pckimlong/kimapp.git
      ref: master
      path: packages/kimapp_generator
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

dependency_overrides:
  # Remove to use pub.dev version
  autoverpod:
    path: /Users/kim/Development/projects/kimapp/pubs/autoverpod
  autoverpod_generator:
    path: /Users/kim/Development/projects/kimapp/pubs/autoverpod_generator
  kimapp_generator:
    path: /Users/kim/Development/projects/kimapp/packages/kimapp_generator
  kimapp_utils:
    path: /Users/kim/Development/projects/kimapp/packages/kimapp_utils
  kimapp_supabase_helper:
    path: /Users/kim/Development/projects/kimapp/packages/kimapp_supabase_helper
  kimapp:
    path: /Users/kim/Development/projects/kimapp/packages/kimapp

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
