create table if not exists public.banners(
    id bigint generated by default as identity primary key,
    note text,
    image_path text not null,
    created_at timestamptz default now() not null,
    is_active boolean default true not null,
    skippable_duration_seconds integer not null default 5
);

-- Only allow one active banner at a time
create unique index if not exists idx_banners_is_active on public.banners (is_active) where is_active = true;


-- trigger to update other banners to inactive when a new banner is created
create or replace function public.update_other_banners_to_inactive()
returns trigger
language plpgsql
as $$
begin
    update public.banners
    set is_active = false
    where id <> new.id;
    return new;
end;
$$;

drop trigger if exists trg_update_other_banners_to_inactive on public.banners;
create trigger trg_update_other_banners_to_inactive
after insert on public.banners
for each row
execute function public.update_other_banners_to_inactive();