create table if not exists public.ads(
    id bigint generated by default as identity primary key,
    title text not null,
    description text not null,
    url text not null,
    image_path text not null,
    button_text text not null,
    created_at timestamptz default now() not null,
    active boolean default true not null
);

-- insert few ads
insert into public.ads (title, description, url, image_path, button_text) values
('Local Bookstore', 'Find your favorite books at your local bookstore', 'https://www.google.com', 'https://i.pinimg.com/736x/be/92/29/be9229efd454bfcb2e67a7ca1e139fa2.jpg', 'Visit Store'),
('Bookstore', 'Get 50% off on your first order', 'https://www.google.com', 'https://i.ytimg.com/vi/zSK-lTX1TTU/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAb0EuZgVoOaeycXgFuDSB5IdvcZg', 'Get 50% off');


alter table public.ads enable row level security;
drop policy if exists "ads: Select policy" on public.ads;
drop policy if exists "ads: Insert policy" on public.ads;
drop policy if exists "ads: Update policy" on public.ads;
drop policy if exists "ads: Delete policy" on public.ads;
create policy "ads: Select policy" on public.ads for select to authenticated using(
    true
);
create policy "ads: Insert policy" on public.ads for insert to authenticated with check (
    true
);
create policy "ads: Update policy" on public.ads for update to authenticated using(
    true
) with check (
    true
);
create policy "ads: Delete policy" on public.ads for delete to authenticated using(
    true
);