name: Release
'on':
  push:
    branches:
      - main
    paths:
      - 'book_swap/**'
      - 'supabase/**'
      - '.github/**'
jobs:
  push_supabase:
    runs-on: ubuntu-latest
    env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        SUPABASE_PROJECT_ID: kcklnkxnhuyyfvytyhtt
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Setup Supabase CLI
          uses: supabase/setup-cli@v1
          with:
            version: latest

        - name: Link to Supabase project
          run: supabase link --project-ref $SUPABASE_PROJECT_ID

        - name: Push change to supabase
          run: supabase db push

  release_apk:
    needs: push_supabase
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./book_swap
    env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        APP_NAME: book-trade

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get flutter dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --target=lib/main.dart --release

      - name: Get version from pubspec.yaml
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | cut -d' ' -f2)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/${APP_NAME}-${{ steps.version.outputs.version }}.apk

      - name: Send APK to Telegram
        run: |
          CURRENT_DATE=$(date +'%Y-%m-%d %H:%M:%S')
          curl -F document=@"build/app/outputs/flutter-apk/${APP_NAME}-${{ steps.version.outputs.version }}.apk" -F caption="Build at: $CURRENT_DATE" https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument?chat_id=${CHAT_ID}